blueprint:
  name: Decrease Integer Helper Value Over Time
  description: Decreases the value of an integer helper over a specified length of time.
  domain: automation
  input:
    helper_entity:
      name: Integer Helper
      description: The integer helper whose value will be decreased.
      selector:
        entity:
          domain: input_number
    duration:
      name: Duration
      description: The length of time (in minutes) over which the helper's value will be decreased.
      default: 60
      selector:
        number:
          min: 1
          max: 1440
          step: 1
          mode: slider
          unit_of_measurement: "minutes"
    minimum_value:
      name: Minimum Value
      description: The minimum value that the integer helper should reach.
      default: 1
      selector:
        number:
          min: 0
          max: 100
          step: 1
          mode: slider

trigger:
  platform: time_pattern
  minutes: "/1"

action:
  service: input_number.set_value
  target:
    entity_id: !input helper_entity
  data:
    value: >
      {% set current_value = states(helper_entity) | int %}
      {% set min_value = minimum_value | int %}
      {% set total_minutes = duration | int %}
      {% set decrease_amount = (current_value - min_value) / total_minutes %}
      {% if current_value - decrease_amount > min_value %}
        {{ current_value - decrease_amount }}
      {% else %}
        {{ min_value }}
      {% endif %}
