blueprint:
  name: Linear Value Modification
  description: Linearly modify the value of an input_number over time based on a schedule entity.
  domain: automation
  input:
    target_input_number:
      name: Target Input Number
      description: The input_number entity whose value you want to modify.
      selector:
        entity:
          domain: input_number
    target_schedule:
      name: Target Schedule
      description: The schedule entity that defines the time period for the value modification.
      selector:
        entity:
          domain: automation
          device_class: schedule
    modification_type:
      name: Modification Type
      description: Choose whether to reduce or increase the value.
      default: reduce
      selector:
        select:
          options:
            - reduce
            - increase
  source_url: https://github.com/AkazaRenn/Home-Assistant/blob/main/linear_value_modification.yaml

mode: restart

trigger:
  platform: state
  entity_id: !input 'target_schedule'
  to: 'on'

action:
  - service: script.turn_on
    target:
      entity_id: script.modify_input_number
    data:
      variables:
        target_input_number: !input 'target_input_number'
        target_schedule: !input 'target_schedule'
        modification_type: !input 'modification_type'

script:
  modify_input_number:
    sequence:
      - variables:
          max_value: "{{ state_attr(target_input_number, 'max') }}"
          min_value: "{{ state_attr(target_input_number, 'min') }}"
          reduction_step: "{{ (max_value - min_value) / (state_attr(target_schedule, 'end_time') | int - state_attr(target_schedule, 'start_time') | int) }}"  # Calculate modification step size
          current_value: "{{ state_attr(target_input_number, 'value') }}"
      - while:
          condition: "{{ is_state(target_schedule, 'on') }}"
          sequence:
            - variables:
                time_passed: "{{ (now().timestamp() - state_attr(target_schedule, 'start_time')) / 60 }}"  # Calculate time passed in minutes
                target_value: "{{ max(current_value - (time_passed * reduction_step), min_value) }}"  # Calculate target value for reduction
            - condition: template
              value_template: "{{ modification_type == 'reduce' and target_value < current_value }}"
            - condition: template
              value_template: "{{ modification_type == 'increase' and target_value > current_value }}"
            - service: input_number.set_value
              target:
                entity_id: !input 'target_input_number'
              data:
                value: "{{ target_value }}"
            - delay:
                seconds: 60
