blueprint:
  name: linear_value_reduction
  description: Linearly reduce the value of an input_number over time based on a schedule entity.
  domain: automation
  input:
    target_input_number:
      name: Target Input Number
      description: The input_number entity whose value you want to reduce.
      selector:
        entity:
          domain: input_number
    target_schedule:
      name: Target Schedule
      description: The schedule entity that defines the time period for the value reduction.
      selector:
        entity:
          domain: automation
          device_class: schedule
  source_url: https://github.com/AkazaRenn/Home-Assistant/blob/main/LinearValueReduction.yaml

mode: single

variables:
  max_value: !input 'target_input_number.attributes.max'
  min_value: !input 'target_input_number.attributes.min'

trigger:
  platform: time_pattern
  minutes: "/1"

condition:
  - condition: template
    value_template: "{{ now().timestamp() >= state_attr('automation.target_schedule', 'start_time') | int }}"

action:
  - variables:
      time_passed: "{{ (now().timestamp() - state_attr('automation.target_schedule', 'start_time')) / 60 }}"  # Calculate time passed in minutes
      duration: "{{ state_attr('automation.target_schedule', 'end_time') | int - state_attr('automation.target_schedule', 'start_time') | int }}"
      reduction_step: "{{ (max_value - min_value) / duration }}"  # Calculate reduction step size
      target_value: "{{ max(max_value - (time_passed * reduction_step), min_value) }}"  # Calculate target value
  - condition: template
    value_template: "{{ target_value < state_attr('input_number.target_input_number', 'value') }}"
  - service: input_number.set_value
    target:
      entity_id: input_number.target_input_number
    data:
      value: "{{ target_value }}"
