blueprint:
  name: Occupancy-activated Light
  description: Turn on a light when motion is detected.
  domain: automation
  source_url: https://github.com/AkazaRenn/Home-Assistant/blob/main/occupancy_activated_light.yaml
  input:
    occupancy_entity:
      name: Occupancy Sensor
      selector:
        entity:
          filter:
            domain: binary_sensor
    light_target:
      name: Light
      selector:
        target:
          entity:
            domain: light
    boolean_confirmer:
      name: Boolean Confirmer
      description: The boolean value to check before turning on the light
      selector:
        entity:
          domain: input_boolean
    boolean_confirmer_expected_state:
      name: Boolean Confirmer Expected State
      selector:
        select:
          options:
            - "on"
            - "off"
    brightness_target:
      name: Brightness Value
      description: The number entity to set the brightness to
      default: null
      selector:
        entity:
          domain: input_number

mode: single

trigger:
  platform: state
  entity_id: !input occupancy_entity
  from: "off"
  to: "on"

condition:
  - condition: state
    entity_id: !input boolean_confirmer
    state: !input boolean_confirmer_expected_state

variables:
  input_occupancy_entity: !input occupancy_entity
  input_light_target: !input light_target
  input_brightness_target: !input brightness_target

action:
  - choose:
      - conditions: "{{ input_brightness_target != None }}"
        sequence:
          - service: light.turn_on
            data:
              brightness_pct: "{{ states(input_brightness_target) | float }}"
            target: "{{ input_light_target }}"
    default:
      - service: light.turn_on
        target: "{{ input_light_target }}"
  - alias: "Wait until the occupancy clearance from device"
    wait_for_trigger:
      platform: state
      entity_id: !input occupancy_entity
      from: "on"
      to: "off"
  - service: light.turn_off
    target: "{{ input_light_target }}"
